### ISSUE TITLE
"asn1.js": "^5.2.0" with error

### ISSUE THREAD

**Issue by lazybusy** [crypto-browserify/parse-asn1#45] opened 2020-08-19 05:40 UTC
SyntaxError: Use of const in strict mode.

**Comment by iceshu** [comment] 2020-08-20 06:35
some error with me

**Comment by sw-uedan** [comment] 2020-09-23 03:40
This issue happens from #37, and seems to be the same as the following issue:
https://github.com/indutny/asn1.js/issues/99

@calvinmetcalf @shrpne 
I think that #37 should be reverted because this commit contains ES6 features, which means that the commit has a non-negligible impact.

Thanks.

**Comment by shrpne** [comment] 2020-09-23 11:34
Duplicate of #41

Btw, i'm personally not against of reverting it in v5 and releasing it under v6

**Comment by sw-uedan** [comment] 2020-09-29 05:16
> Duplicate of #41

Oh, thanks.

**Comment by ljharb** [comment] 2024-03-05 07:23
Closing as a duplicate of #41.

**Closed as not planned by ljharb** 2024-03-05 07:23 UTC
